name: loveinloop
description: "Aplicativo para criar e compartilhar presentes digitais personalizados."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  audioplayers: ^6.8.0
  carousel_slider: ^5.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  record: ^7.1.0



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
 
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

